# Generated by Django 3.2.9 on 2021-11-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0003_alter_notesmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
